<a href="https://colab.research.google.com/github/Samarjeet09/MiniProjects/blob/main/Mini%20Project-14%3A%20Cosine%20Similarity/Cosine_Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cosine Similarity
- **Cosine similarity** is a measure of similarity between two non-zero vectors of an inner product space that measures the cosine of the angle between them.
**Similarity = (A.B) / (||A||.||B||)** where A and B are vectors.
-   A.B is dot product of A and B: It is computed as sum of element-wise product of A and B.
-   ||A|| is L2 norm of A: It is computed as square root of the sum of squares of elements of the vector A.

In [1]:
import numpy as np
import random as r
from numpy.linalg import norm

In [6]:
A = np.array([r.randint(0,9) for _ in range(15)])
B = np.array([r.randint(0,9) for _ in range(15)])
print("A:", A)
print("B:", B)

A: [3 1 7 4 7 4 8 1 1 7 3 8 8 2 7]
B: [0 5 8 2 9 2 7 4 9 1 8 9 9 6 7]


In [7]:
# compute cosine similarity
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)

Cosine Similarity: 0.8364720763965733


# For 2D array


In [22]:
A = np.array([[ r.randint(0,9)for _ in range(5)] for _ in range(5)])
B = np.array([[ r.randint(0,9)for _ in range(5)] for _ in range(5)])
print("A:", A)
print("B:", B)

A: [[6 8 4 4 0]
 [5 4 0 2 8]
 [7 4 5 6 6]
 [4 4 0 1 0]
 [9 5 0 4 1]]
B: [[3 6 0 6 5]
 [9 7 5 1 2]
 [0 8 0 3 7]
 [2 6 9 2 0]
 [8 2 2 0 9]]


In [23]:
cosine = np.sum(A*B, axis=1)/(norm(A, axis=1)*norm(B, axis=1))
print("Cosine Similarity:\n", cosine)

Cosine Similarity:
 [0.76085625 0.68907763 0.65441072 0.52937928 0.66335059]


# cosine similarity is Row Wise